name: Build and Test

on:
  # schedule:
  #   - cron: "*/50 * * * *" # every 50 minutes
  workflow_dispatch: # allows manual runs

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install sentry-cli
        run: |
          pip install sentry-cli

      - name: Setup Unreal Engine (placeholder)
        run: |
          echo "Note: This is a placeholder for Unreal Engine setup"
          echo "In a real setup, we would need to:"
          echo "1. Download Unreal Engine 5.5 from Epic Games"
          echo "2. Install it on the runner"
          echo "3. Or use a pre-built Docker image with Unreal Engine"
          echo ""
          echo "For now, this workflow shows the concept without actual building"

      - name: Build game (placeholder)
        run: |
          echo "Building Unreal game..."
          echo "This would use Unreal Engine's build tools to compile the project"
          echo "Similar to: RunUAT.bat BuildCookRun -project=SentryTower.uproject -platform=Win64 -cook -build -stage -package"
          echo ""
          echo "Since we don't have Unreal Engine installed, this is just a placeholder"

      - name: Upload debug symbols (placeholder)
        if: ${{ env.SENTRY_AUTH_TOKEN != '' }}
        run: |
          echo "Uploading debug symbols..."
          echo "This would upload .exe and .pdb files to Sentry"
          echo "sentry-cli debug-files upload --include-sources Builds/Windows/SentryTower.exe Builds/Windows/SentryTower.pdb"
          echo ""
          echo "Since we don't have built files, this is just a placeholder"

      - name: Run simulation (placeholder)
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          echo "Running Unreal demo..."
          echo "This would run: Builds/Windows/SentryTower.exe -Unattended -nullrhi --idle"
          echo "Similar to how Godot runs: ./tools/godot.windows.template_release.x86_64.exe --path . --automate --dsn=${SENTRY_DSN}"
          echo ""
          echo "Since we don't have a built game, this is just a placeholder"
          echo "The workflow structure is ready for when Unreal Engine is available"
