name: Run Demo

on:
  schedule: # Run every 50 minutes
    - cron: '*/50 * * * *'
  workflow_dispatch: # Manual trigger
    inputs:
      platforms:
        description: 'Platforms to run'
        type: choice
        default: all
        options:
          - all
          - windows
          - linux
          - macos
          - android

concurrency:
  group: run-demo
  cancel-in-progress: false

jobs:
  run-windows:
    if: ${{ github.event_name != 'workflow_dispatch' || contains(fromJSON('["all","windows"]'), inputs.platforms) }}
    uses: ./.github/workflows/run-windows.yml
    secrets: inherit

  run-linux:
    if: ${{ github.event_name != 'workflow_dispatch' || contains(fromJSON('["all","linux"]'), inputs.platforms) }}
    uses: ./.github/workflows/run-linux.yml
    secrets: inherit

  run-macos:
    if: ${{ github.event_name != 'workflow_dispatch' || contains(fromJSON('["all","macos"]'), inputs.platforms) }}
    uses: ./.github/workflows/run-macos.yml
    secrets: inherit

  run-android:
    if: ${{ github.event_name != 'workflow_dispatch' || contains(fromJSON('["all","android"]'), inputs.platforms) }}
    uses: ./.github/workflows/run-android.yml
    secrets: inherit
