name: run-demo

on:
  # schedule:
  #   - cron: '0 */2 * * *' # every two hours
  workflow_dispatch:

jobs:
  run:
    name: Run Demo
    runs-on: windows-latest

    steps:
      - name: Get latest build run
        id: get-run
        run: |
          $runs = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci.yml/runs?status=success&per_page=1" -Headers @{Authorization="Bearer ${{ secrets.GITHUB_TOKEN }}"}
          $runId = $runs.workflow_runs[0].id
          echo "run-id=$runId" >> $env:GITHUB_OUTPUT

      - name: Download SentryTower
        uses: actions/download-artifact@v4
        with:
          name: SentryTower
          path: ./artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run.outputs.run-id }}

      - name: Extract artifact
        run: |
          # List downloaded files for debugging
          Get-ChildItem -Path "./artifacts" -Filter "*.zip"
          
          # Find the zip file
          $zipFile = Get-ChildItem -Path "./artifacts" -Filter "*.zip" | Select-Object -First 1
          if (!$zipFile) {
            Write-Error "No zip file found in artifacts directory"
            exit 1
          }
          
          Write-Output "Extracting: $($zipFile.Name)"
          Expand-Archive -Path $zipFile.FullName -DestinationPath "." -Force

      - name: Run simulation
        run: |
          if (!(Test-Path "SentryTower.exe")) {
            Write-Error "SentryTower.exe not found after extraction"
            exit 1
          }
          .\SentryTower.exe -Unattended -nullrhi --idle
          if ($LASTEXITCODE -eq 0) {
            Write-Error "Expected non-zero exit code but got 0"
            exit 1
          }
          Write-Output "Simulation completed with expected non-zero exit code: $LASTEXITCODE"