name: run-demo

on:
  # schedule:
  #   - cron: '0 */2 * * *' # every two hours
  workflow_dispatch:

jobs:
  run:
    name: Run Demo
    runs-on: windows-latest

    steps:
      - name: Get latest build run
        id: get-run
        run: |
          $runs = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci.yml/runs?status=success&per_page=1" -Headers @{Authorization="Bearer ${{ secrets.GITHUB_TOKEN }}"}
          $runId = $runs.workflow_runs[0].id
          echo "run-id=$runId" >> $env:GITHUB_OUTPUT

      - name: Download SentryTower
        id: download
        uses: actions/download-artifact@v4
        with:
          name: SentryTower
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run.outputs.run-id }}

      - name: Start Windows Docker Container
        run: |
          $downloadPath = "${{ steps.download.outputs.download-path }}"
          Write-Output "Download path: $downloadPath"
          docker run -td `
            --name unreal `
            --volume "${downloadPath}:C:\workspace" `
            --workdir C:\workspace `
            mcr.microsoft.com/windows/server:ltsc2022
      
      - name: Run Simulation
        run: |
          docker exec unreal C:\workspace\SentryTower.exe -Unattended -nullrhi --idle